### ISSUE TITLE
allow array of objects and extra styling for the alphabet list on the right

### ISSUE THREAD

**Issue by taofeeq-deru** [xVanTuring/Alphabet-List#2]
Hi, 
I'd love to contribute to this project.

Want to allow it to take possibly take an array of objects, and also allow styling of the the alphabet list on the right, one could want to increase the font size or change the color

I also had an issue with the list not scrolling to the selected alphabet which I'd love to fix

Thank you.

**Comment by xVanTuring** [comment]
Glad to hear that, You are welcome to create a pr.

**Comment by taofeeq-deru** [comment]
> Glad to hear that, You are welcome to create a pr.

Hi

I've raised a PR for this, please review

**Comment by xVanTuring** [comment]
PR(https://github.com/xVanTuring/Alphabet-List/pull/3) is merged, I'll try to make some other changes, and push the new version to npm asap

**Comment by xVanTuring** [comment]
@Taofeeq-deru A new version [0.2.0](https://www.npmjs.com/package/react-alphabet-list) is now released. Thanks for your contribution❤!

**Comment by taofeeq-deru** [comment]
@xVanTuring You're welcome. Thank you too
